-- attendance.user_id is introduced by the later
-- 20260727100000_link_attendance_to_users migration. The foreign key must be
-- created there so a fresh shadow database can replay migrations in order.
