const { ROLE_KEYS, toRoleKey } = require("./roles");

const PERMISSIONS = {
  CREATE_ADMIN: "CREATE_ADMIN",
  VIEW_ADMINS: "VIEW_ADMINS",
  UPDATE_ADMIN: "UPDATE_ADMIN",
  DELETE_ADMIN: "DELETE_ADMIN",
  CREATE_DEPARTMENT: "CREATE_DEPARTMENT",
  VIEW_DEPARTMENTS: "VIEW_DEPARTMENTS",
  UPDATE_DEPARTMENT: "UPDATE_DEPARTMENT",
  DELETE_DEPARTMENT: "DELETE_DEPARTMENT",
  CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
  VIEW_EMPLOYEES: "VIEW_EMPLOYEES",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  IMPORT_ATTENDANCE: "IMPORT_ATTENDANCE",
  VIEW_SYSTEM_SUMMARY: "VIEW_SYSTEM_SUMMARY",
  VIEW_TEAM_ATTENDANCE: "VIEW_TEAM_ATTENDANCE",
  VIEW_OWN_ATTENDANCE: "VIEW_OWN_ATTENDANCE",
  VIEW_REPORTS: "VIEW_REPORTS",
  CREATE_LEAVE: "CREATE_LEAVE",
  VIEW_OWN_LEAVES: "VIEW_OWN_LEAVES",
  VIEW_TEAM_LEAVES: "VIEW_TEAM_LEAVES",
  VIEW_ALL_LEAVES: "VIEW_ALL_LEAVES",
  APPROVE_LEAVE: "APPROVE_LEAVE",
  REJECT_LEAVE: "REJECT_LEAVE",
  CANCEL_LEAVE: "CANCEL_LEAVE"
};

const ROLE_PERMISSIONS = {
  [ROLE_KEYS.SUPER_ADMIN]: [
    PERMISSIONS.CREATE_ADMIN,
    PERMISSIONS.VIEW_ADMINS,
    PERMISSIONS.UPDATE_ADMIN,
    PERMISSIONS.DELETE_ADMIN,
    PERMISSIONS.CREATE_DEPARTMENT,
    PERMISSIONS.VIEW_DEPARTMENTS,
    PERMISSIONS.UPDATE_DEPARTMENT,
    PERMISSIONS.DELETE_DEPARTMENT,
    PERMISSIONS.CREATE_EMPLOYEE,
    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.UPDATE_EMPLOYEE,
    PERMISSIONS.DELETE_EMPLOYEE,
    PERMISSIONS.IMPORT_ATTENDANCE,
    PERMISSIONS.VIEW_SYSTEM_SUMMARY,
    PERMISSIONS.VIEW_TEAM_ATTENDANCE,
    PERMISSIONS.VIEW_OWN_ATTENDANCE,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ALL_LEAVES,
    PERMISSIONS.VIEW_TEAM_LEAVES,
    PERMISSIONS.APPROVE_LEAVE,
    PERMISSIONS.REJECT_LEAVE
  ],

  [ROLE_KEYS.ADMIN]: [
    PERMISSIONS.CREATE_LEAVE,
    PERMISSIONS.CREATE_EMPLOYEE,
    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.UPDATE_EMPLOYEE,
    PERMISSIONS.DELETE_EMPLOYEE,
    PERMISSIONS.IMPORT_ATTENDANCE,
    PERMISSIONS.VIEW_SYSTEM_SUMMARY,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_OWN_LEAVES,
    PERMISSIONS.VIEW_ALL_LEAVES,
    PERMISSIONS.VIEW_TEAM_LEAVES,
    PERMISSIONS.APPROVE_LEAVE,
    PERMISSIONS.REJECT_LEAVE,
    PERMISSIONS.CANCEL_LEAVE
  ],

  [ROLE_KEYS.EMPLOYEE]: [
    PERMISSIONS.CREATE_LEAVE,
    PERMISSIONS.VIEW_OWN_ATTENDANCE,
    PERMISSIONS.VIEW_OWN_LEAVES,
    PERMISSIONS.CANCEL_LEAVE
  ]
};

const normalizePermission = (permission) => {
  return String(permission || "").trim().toUpperCase().replace(/[\s-]+/g, "_");
};

const hasPermission = (role, permission) => {
  return (
    ROLE_PERMISSIONS[toRoleKey(role)]?.includes(normalizePermission(permission)) || false
  );
};

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission
};
