const { ROLE_KEYS, toRoleKey } = require("./roles");

const PERMISSIONS = {
  MANAGE_ADMINS: "MANAGE_ADMINS",
  MANAGE_DEPARTMENTS: "MANAGE_DEPARTMENTS",
  MANAGE_EMPLOYEES: "MANAGE_EMPLOYEES",
  VIEW_SYSTEM_SUMMARY: "VIEW_SYSTEM_SUMMARY",
  VIEW_TEAM_ATTENDANCE: "VIEW_TEAM_ATTENDANCE",
  VIEW_OWN_ATTENDANCE: "VIEW_OWN_ATTENDANCE",
  VIEW_REPORTS: "VIEW_REPORTS",
  CREATE_LEAVE: "CREATE_LEAVE",
  VIEW_OWN_LEAVE: "VIEW_OWN_LEAVE",
  VIEW_TEAM_LEAVE: "VIEW_TEAM_LEAVE",
  VIEW_ALL_LEAVES: "VIEW_ALL_LEAVES",
  APPROVE_LEAVE: "APPROVE_LEAVE",
  REJECT_LEAVE: "REJECT_LEAVE",
  CANCEL_LEAVE: "CANCEL_LEAVE"
};

const ROLE_PERMISSIONS = {
  [ROLE_KEYS.SUPER_ADMIN]: [
    PERMISSIONS.MANAGE_ADMINS,
    PERMISSIONS.MANAGE_DEPARTMENTS,
    PERMISSIONS.MANAGE_EMPLOYEES,
    PERMISSIONS.VIEW_SYSTEM_SUMMARY,
    PERMISSIONS.VIEW_TEAM_ATTENDANCE,
    PERMISSIONS.VIEW_OWN_ATTENDANCE,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ALL_LEAVES,
    PERMISSIONS.VIEW_TEAM_LEAVE,
    PERMISSIONS.APPROVE_LEAVE,
    PERMISSIONS.REJECT_LEAVE
  ],

  [ROLE_KEYS.ADMIN]: [
    PERMISSIONS.CREATE_LEAVE,
    PERMISSIONS.MANAGE_EMPLOYEES,
    PERMISSIONS.VIEW_SYSTEM_SUMMARY,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_OWN_LEAVE,
    PERMISSIONS.VIEW_ALL_LEAVES,
    PERMISSIONS.VIEW_TEAM_LEAVE,
    PERMISSIONS.APPROVE_LEAVE,
    PERMISSIONS.REJECT_LEAVE,
    PERMISSIONS.CANCEL_LEAVE
  ],

  [ROLE_KEYS.PROJECT_MANAGER]: [
    PERMISSIONS.CREATE_LEAVE,
    PERMISSIONS.VIEW_TEAM_ATTENDANCE,
    PERMISSIONS.VIEW_OWN_LEAVE,
    PERMISSIONS.VIEW_TEAM_LEAVE,
    PERMISSIONS.APPROVE_LEAVE,
    PERMISSIONS.REJECT_LEAVE,
    PERMISSIONS.CANCEL_LEAVE
  ],

  [ROLE_KEYS.EMPLOYEE]: [
    PERMISSIONS.CREATE_LEAVE,
    PERMISSIONS.VIEW_OWN_ATTENDANCE,
    PERMISSIONS.VIEW_OWN_LEAVE,
    PERMISSIONS.CANCEL_LEAVE
  ]
};

const normalizePermission = (permission) => {
  return String(permission || "").trim().toUpperCase().replace(/[\s-]+/g, "_");
};

const hasPermission = (role, permission) => {
  return (
    ROLE_PERMISSIONS[toRoleKey(role)]?.includes(normalizePermission(permission)) || false
  );
};

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission
};
