const { ROLE_KEYS } = require("./roles");

const PERMISSIONS = {
  CREATE_ADMIN: "CREATE_ADMIN",
  CREATE_EMPLOYEE: "CREATE_EMPLOYEE",

  VIEW_ALL_LEAVES: "VIEW_ALL_LEAVES",
  VIEW_OWN_LEAVES: "VIEW_OWN_LEAVES",

  APPLY_LEAVE: "APPLY_LEAVE",

  APPROVE_PM: "APPROVE_PM",
  APPROVE_HR: "APPROVE_HR",
  APPROVE_SUPER_ADMIN: "APPROVE_SUPER_ADMIN"
};

const ROLE_PERMISSIONS = {
  [ROLE_KEYS.SUPER_ADMIN]: [
    PERMISSIONS.CREATE_ADMIN,
    PERMISSIONS.CREATE_EMPLOYEE,

    PERMISSIONS.VIEW_ALL_LEAVES,

    PERMISSIONS.APPROVE_SUPER_ADMIN
  ],

  [ROLE_KEYS.ADMIN]: [
    PERMISSIONS.CREATE_EMPLOYEE,

    PERMISSIONS.VIEW_ALL_LEAVES,

    PERMISSIONS.APPROVE_HR
  ],

  [ROLE_KEYS.PROJECT_MANAGER]: [
    PERMISSIONS.VIEW_ALL_LEAVES,

    PERMISSIONS.APPROVE_PM
  ],

  [ROLE_KEYS.EMPLOYEE]: [
    PERMISSIONS.APPLY_LEAVE,

    PERMISSIONS.VIEW_OWN_LEAVES
  ]
};

const hasPermission = (role, permission) => {
  return (
    ROLE_PERMISSIONS[role]?.includes(permission) || false
  );
};

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission
};